Version = "1.0.0-Alpha"

# Development settings
[dev]
enabled = false
username = "dev"
password = "dev"

# Console settings
[console]
session_timeout = 300  # seconds (5 minutes)
debug = false  # Enable/disable debug messages

# Security settings
[security]
max_login_attempts = 3
lockout_duration = 300  # seconds (5 minutes)
pepper = "rKyT8L7BUIJ9gpMb5MWFXO4gcYKVBv09"  # Add this line